--- Essa query retorna a quantidade exata de individuos com cadastro ativo no ANOMES ref

SELECT COUNT(DISTINCT P.CO_CHV_NATURAL_PESSOA) AS QT_PESSOAS_CADASTRADAS
FROM P_CADASTRO_ODS_202511.TB_PESSOA_04 P
JOIN P_CADASTRO_ODS_202511.TB_FAMILIA_01 F
  ON P.CO_FAMILIAR_FAM = F.CO_FAMILIAR_FAM
WHERE F.CO_EST_CADASTRAL_FAM NOT IN (1, 2, 4)
	AND P.CO_EST_CADASTRAL_MEMB = 3;