/* ============================================================================
   OBJETIVO (DEDUP POR CPF - SOMENTE OCORRÊNCIA VIGENTE):
     Retornar DOC + PESSOA + FAMÍLIA + CONTATO + ESCOLARIDADE (classificação oficial)
     + flags:
        - PBF: família vigente está na folha RF_FOLHA = ANOMES_ODS + 1
        - PRE: família vigente está na pré-habilitação RF_FOLHA = ANOMES_ODS
     filtrando por CODIBGE.

   DEDUP:
     - Considera SOMENTE universo válido:
         P.CO_EST_CADASTRAL_MEMB = 3
         F.CO_EST_CADASTRAL_FAM NOT IN (1,2,4)
     - Escolhe a ocorrência "mais vigente" por CPF:
         maior DT_ATUAL_MEMB, depois DT_ATUALIZACAO_FAM, depois CO_CHV_NATURAL_PESSOA
   ============================================================================ */

DATABASE P_CADASTRO_ODS_202512;

WITH params AS (
  SELECT
    '5200258' AS CODIBGE_ALVO,   -- <<< CODIBGE (7 dígitos)
    202512    AS ANOMES_ODS
),

/* ===== RF_FOLHA PBF = ANOMES + 1 / RF_FOLHA PRE = ANOMES ===== */
ref AS (
  SELECT
    prm.CODIBGE_ALVO,
    prm.ANOMES_ODS,

    (EXTRACT(YEAR  FROM ADD_MONTHS(CAST((CAST(prm.ANOMES_ODS AS INTEGER) * 100 + 1) AS DATE FORMAT 'YYYYMMDD'), 1)) * 100
   + EXTRACT(MONTH FROM ADD_MONTHS(CAST((CAST(prm.ANOMES_ODS AS INTEGER) * 100 + 1) AS DATE FORMAT 'YYYYMMDD'), 1))
    ) AS RF_FOLHA_PBF,

    prm.ANOMES_ODS AS RF_FOLHA_PRE
  FROM params prm
),

/* ===== FAMÍLIAS NA FOLHA (ANOMES + 1) ===== */
folha_bf AS (
  SELECT DISTINCT
         FOL.CO_FAMILIAR
  FROM P_DEBEN_ACC.VW_FOLHA_PAGAMENTO FOL
  CROSS JOIN ref r
  WHERE FOL.RF_FOLHA = r.RF_FOLHA_PBF
),

/* ===== FAMÍLIAS PRÉ-HABILITADAS (MESMO ANOMES) ===== */
pre_hab AS (
  SELECT DISTINCT
         PRE.CO_FAMILIAR
  FROM P_DEBEN_ACC.VW_PRE_HABILITACAO_PBF PRE
  CROSS JOIN ref r
  WHERE PRE.RF_FOLHA = r.RF_FOLHA_PRE
),

/* ===== BASE VÁLIDA (ATIVO) + ESCOLARIDADE + CONTATO ===== */
base_valid_raw AS (
  SELECT
    /* CPF para dedup */
    DOC.NU_CPF_PESSOA                              AS CPF,

    /* ========== TB_DOCUMENTO_05 ========== */
    DOC.CO_FAMILIAR_FAM           AS DOC_CO_FAMILIAR_FAM,
    DOC.CO_CHV_NATURAL_PESSOA     AS DOC_CO_CHV_NATURAL_PESSOA,
    DOC.NU_CPF_PESSOA             AS DOC_NU_CPF_PESSOA,
    DOC.CO_CERTIDAO_CIVIL_PESSOA  AS DOC_CO_CERTIDAO_CIVIL_PESSOA,
    DOC.NO_CARTORIO_PESSOA        AS DOC_NO_CARTORIO_PESSOA,
    DOC.NU_IDENTIDADE_PESSOA      AS DOC_NU_IDENTIDADE_PESSOA,
    DOC.SG_UF_IDENT_PESSOA        AS DOC_SG_UF_IDENT_PESSOA,
    DOC.NU_TITULO_ELEITOR_PESSOA  AS DOC_NU_TITULO_ELEITOR_PESSOA,

    /* ========== TB_PESSOA_04 ========== */
    P.CO_FAMILIAR_FAM             AS PES_CO_FAMILIAR_FAM,
    P.CO_CHV_NATURAL_PESSOA       AS PES_CO_CHV_NATURAL_PESSOA,
    P.DT_CADASTRAMENTO_MEMB       AS PES_DT_CADASTRAMENTO_MEMB,
    P.DT_ATUAL_MEMB               AS PES_DT_ATUAL_MEMB,
    P.CO_EST_CADASTRAL_MEMB       AS PES_CO_EST_CADASTRAL_MEMB,
    P.NO_PESSOA                   AS PES_NO_PESSOA,
    P.NU_NIS_PESSOA               AS PES_NU_NIS_PESSOA,
    P.NO_APELIDO_PESSOA           AS PES_NO_APELIDO_PESSOA,
    P.DT_NASC_PESSOA              AS PES_DT_NASC_PESSOA,
    P.CO_ORIGEM_FAMILIA_PESSOA    AS PES_CO_ORIGEM_FAMILIA_PESSOA,
    P.IN_ORIGEM_ALTERACAO_PESSOA  AS PES_IN_ORIGEM_ALTERACAO_PESSOA,
    P.CO_CHV_NAT_PES_ATUAL        AS PES_CO_CHV_NAT_PES_ATUAL,
    P.CO_CHV_NAT_PES_ORIGINAL     AS PES_CO_CHV_NAT_PES_ORIGINAL,
    P.NU_NIS_ORIGINAL             AS PES_NU_NIS_ORIGINAL,
    P.IN_TRANSFERENCIA_PESSOA     AS PES_IN_TRANSFERENCIA_PESSOA,

    /* ========== ESCOLARIDADE (CLASSIFICAÇÃO OFICIAL) ========== */
    CASE
      /* EFI */
      WHEN (ESC.CO_SABE_LER_ESCREVER_MEMB = 1 AND ESC.IN_FREQUENTA_ESCOLA_MEMB IN (1,2)
            AND ESC.CO_CURSO_FREQUENTA_MEMB = 7
            AND ESC.CO_ANO_SERIE_FREQUENTA_MEMB IN (1,10))
        OR (ESC.CO_SABE_LER_ESCREVER_MEMB = 1 AND ESC.IN_FREQUENTA_ESCOLA_MEMB IN (1,2)
            AND ESC.CO_CURSO_FREQUENTA_MEMB IN (10,11))
        OR (ESC.CO_SABE_LER_ESCREVER_MEMB = 1 AND ESC.IN_FREQUENTA_ESCOLA_MEMB = 3
            AND ESC.CO_CURSO_FREQ_PESSOA_MEMB = 5
            AND ESC.CO_ANO_SERIE_FREQUENTOU_MEMB IN (8,10))
        OR (ESC.CO_SABE_LER_ESCREVER_MEMB = 1 AND ESC.IN_FREQUENTA_ESCOLA_MEMB = 3
            AND ESC.CO_CURSO_FREQ_PESSOA_MEMB = 6
            AND ESC.CO_ANO_SERIE_FREQUENTOU_MEMB IN (9,10))
        OR (ESC.CO_SABE_LER_ESCREVER_MEMB = 1 AND ESC.IN_FREQUENTA_ESCOLA_MEMB = 3
            AND ESC.CO_CURSO_FREQ_PESSOA_MEMB = 7
            AND ESC.CO_ANO_SERIE_FREQUENTOU_MEMB IN (8,10))
        OR (ESC.CO_SABE_LER_ESCREVER_MEMB = 1 AND ESC.IN_FREQUENTA_ESCOLA_MEMB = 3
            AND ESC.CO_CURSO_FREQ_PESSOA_MEMB = 11)
      THEN 'EFI'

      /* EFC */
      WHEN (ESC.CO_SABE_LER_ESCREVER_MEMB = 1 AND ESC.IN_FREQUENTA_ESCOLA_MEMB IN (1,2)
            AND ESC.CO_CURSO_FREQUENTA_MEMB = 4
            AND ESC.CO_ANO_SERIE_FREQUENTA_MEMB IN (2,3,4,5,6,7,8))
        OR (ESC.CO_SABE_LER_ESCREVER_MEMB = 1 AND ESC.IN_FREQUENTA_ESCOLA_MEMB IN (1,2)
            AND ESC.CO_CURSO_FREQUENTA_MEMB = 5
            AND ESC.CO_ANO_SERIE_FREQUENTA_MEMB IN (3,4,5,6,7,8,9))
        OR (ESC.CO_SABE_LER_ESCREVER_MEMB = 1 AND ESC.IN_FREQUENTA_ESCOLA_MEMB IN (1,2)
            AND ESC.CO_CURSO_FREQUENTA_MEMB = 10)
        OR (ESC.CO_SABE_LER_ESCREVER_MEMB = 1 AND ESC.IN_FREQUENTA_ESCOLA_MEMB = 3
            AND ESC.CO_CURSO_FREQ_PESSOA_MEMB = 4
            AND ESC.CO_ANO_SERIE_FREQUENTOU_MEMB IN (1,2,3,4,10))
        OR (ESC.CO_SABE_LER_ESCREVER_MEMB = 1 AND ESC.IN_FREQUENTA_ESCOLA_MEMB = 3
            AND ESC.CO_CURSO_FREQ_PESSOA_MEMB = 5
            AND ESC.CO_ANO_SERIE_FREQUENTOU_MEMB IN (5,6,7))
        OR (ESC.CO_SABE_LER_ESCREVER_MEMB = 1 AND ESC.IN_FREQUENTA_ESCOLA_MEMB = 3
            AND ESC.CO_CURSO_FREQ_PESSOA_MEMB = 6
            AND ESC.CO_ANO_SERIE_FREQUENTOU_MEMB IN (2,3,4,5,6,7,8))
        OR (ESC.CO_SABE_LER_ESCREVER_MEMB = 1 AND ESC.IN_FREQUENTA_ESCOLA_MEMB = 3
            AND ESC.CO_CURSO_FREQ_PESSOA_MEMB = 7
            AND ESC.CO_ANO_SERIE_FREQUENTOU_MEMB IN (1,2,3,4,5,6,7))
        OR (ESC.CO_SABE_LER_ESCREVER_MEMB = 1 AND ESC.IN_FREQUENTA_ESCOLA_MEMB = 3
            AND ESC.CO_CURSO_FREQ_PESSOA_MEMB = 10)
      THEN 'EFC'

      /* EMI */
      WHEN (ESC.CO_SABE_LER_ESCREVER_MEMB = 1 AND ESC.IN_FREQUENTA_ESCOLA_MEMB IN (1,2)
            AND ESC.CO_CURSO_FREQUENTA_MEMB = 7
            AND ESC.CO_ANO_SERIE_FREQUENTA_MEMB IN (2,3,4))
        OR (ESC.CO_SABE_LER_ESCREVER_MEMB = 1 AND ESC.IN_FREQUENTA_ESCOLA_MEMB = 3
            AND ESC.CO_CURSO_FREQ_PESSOA_MEMB IN (8,9)
            AND ESC.CO_ANO_SERIE_FREQUENTOU_MEMB IN (1,2))
      THEN 'EMI'

      /* EMC */
      WHEN (ESC.CO_SABE_LER_ESCREVER_MEMB = 1 AND ESC.IN_FREQUENTA_ESCOLA_MEMB IN (1,2)
            AND ESC.CO_CURSO_FREQUENTA_MEMB = 14)
        OR (ESC.CO_SABE_LER_ESCREVER_MEMB = 1 AND ESC.IN_FREQUENTA_ESCOLA_MEMB = 3
            AND ESC.CO_CURSO_FREQ_PESSOA_MEMB IN (8,9)
            AND ESC.CO_ANO_SERIE_FREQUENTOU_MEMB IN (3,4,10))
        OR (ESC.CO_SABE_LER_ESCREVER_MEMB = 1 AND ESC.IN_FREQUENTA_ESCOLA_MEMB = 3
            AND ESC.CO_CURSO_FREQ_PESSOA_MEMB = 12)
      THEN 'EMC'

      /* ES ou + */
      WHEN (ESC.CO_SABE_LER_ESCREVER_MEMB = 1 AND ESC.IN_FREQUENTA_ESCOLA_MEMB IN (1,2)
            AND ESC.CO_CURSO_FREQUENTA_MEMB = 13)
        OR (ESC.CO_SABE_LER_ESCREVER_MEMB = 1 AND ESC.IN_FREQUENTA_ESCOLA_MEMB = 3
            AND ESC.CO_CURSO_FREQ_PESSOA_MEMB = 13)
      THEN 'ES OU +'

      ELSE 'Não Informado'
    END AS ESCOLARIDADE,

    /* ========== TB_FAMILIA_01 ========== */
    F.CO_FAMILIAR_FAM             AS FAM_CO_FAMILIAR_FAM,
    F.DT_CADASTRO_FAM             AS FAM_DT_CADASTRO_FAM,
    F.DT_ULT_ATUAL_FAM            AS FAM_DT_ULT_ATUAL_FAM,
    F.CO_EST_CADASTRAL_FAM        AS FAM_CO_EST_CADASTRAL_FAM,
    F.IN_CADASTRO_VALIDO_FAM      AS FAM_IN_CADASTRO_VALIDO_FAM,
    F.CO_CONDICAO_CADASTRO_FAM    AS FAM_CO_CONDICAO_CADASTRO_FAM,
    F.CO_MODALIDADE_OPER_FAM      AS FAM_CO_MODALIDADE_OPER_FAM,
    F.CO_ORIGEM_FAMILIA_FAM       AS FAM_CO_ORIGEM_FAMILIA_FAM,
    F.DT_CDSTR_ATUAL_FMLA         AS FAM_DT_CDSTR_ATUAL_FMLA,
    F.IN_FAM_ALTERADA_V7          AS FAM_IN_FAM_ALTERADA_V7,
    F.DT_ATUALIZACAO_FAM          AS FAM_DT_ATUALIZACAO_FAM,

    /* ========== TB_CONTATO_09 ========== */
    CONT.NU_DDD_CONTATO_1_FAM      AS CONT_DDD_1,
    CONT.NU_TEL_CONTATO_1_FAM      AS CONT_TEL_1,
    CONT.NU_DDD_CONTATO_2_FAM      AS CONT_DDD_2,
    CONT.NU_TEL_CONTATO_2_FAM      AS CONT_TEL_2,
    CONT.IN_TIPO_EMAIL_FAM         AS CONT_TIPO_EMAIL,
    CONT.DS_EMAIL_FAM              AS CONT_EMAIL,

    /* ===== para dedup/ordenação ===== */
    P.DT_ATUAL_MEMB                AS ORD_DT_ATUAL_MEMB,
    F.DT_ATUALIZACAO_FAM           AS ORD_DT_ATUALIZACAO_FAM,
    P.CO_CHV_NATURAL_PESSOA        AS ORD_CHAVE_PESSOA

  FROM P_CADASTRO_ODS_202512.TB_DOCUMENTO_05 DOC
  JOIN P_CADASTRO_ODS_202512.TB_PESSOA_04 P
    ON P.CO_CHV_NATURAL_PESSOA = DOC.CO_CHV_NATURAL_PESSOA
  JOIN P_CADASTRO_ODS_202512.TB_FAMILIA_01 F
    ON F.CO_FAMILIAR_FAM = P.CO_FAMILIAR_FAM
  LEFT JOIN P_CADASTRO_ODS_202512.TB_ESCOLARIDADE_07 ESC
    ON ESC.CO_CHV_NATURAL_PESSOA = P.CO_CHV_NATURAL_PESSOA
  LEFT JOIN P_CADASTRO_ODS_202512.TB_CONTATO_09 CONT
    ON CONT.CO_FAMILIAR_FAM = P.CO_FAMILIAR_FAM
  CROSS JOIN ref r
  WHERE
    /* filtro por CODIBGE */
    ( LPAD(TRIM(CAST(F.CO_MUNIC_IBGE_2_FAM AS VARCHAR(2))), 2, '0')
      || LPAD(TRIM(CAST(F.CO_MUNIC_IBGE_5_FAM AS VARCHAR(5))), 5, '0')
    ) = r.CODIBGE_ALVO

    /* universo válido (ativo) */
    AND DOC.NU_CPF_PESSOA IS NOT NULL
    AND P.CO_EST_CADASTRAL_MEMB = 3
    AND F.CO_EST_CADASTRAL_FAM NOT IN (1,2,4)
),

/* ===== DEDUP: 1 LINHA POR CPF (OCORRÊNCIA VIGENTE) ===== */
base_vigente AS (
  SELECT *
  FROM base_valid_raw
  QUALIFY ROW_NUMBER() OVER (
    PARTITION BY CPF
    ORDER BY
      ORD_DT_ATUAL_MEMB DESC,
      ORD_DT_ATUALIZACAO_FAM DESC,
      ORD_CHAVE_PESSOA
  ) = 1
)

SELECT
  b.*,

  /* FLAGS calculadas SOMENTE com a família vigente */
  CASE WHEN FB.CO_FAMILIAR IS NOT NULL THEN 'SIM' ELSE 'NAO' END AS FAMILIA_NA_FOLHA_PBF,
  CASE WHEN PH.CO_FAMILIAR IS NOT NULL THEN 'SIM' ELSE 'NAO' END AS FAMILIA_PRE_HABILITADA

FROM base_vigente b
LEFT JOIN folha_bf FB
  ON FB.CO_FAMILIAR = b.FAM_CO_FAMILIAR_FAM
LEFT JOIN pre_hab PH
  ON PH.CO_FAMILIAR = b.FAM_CO_FAMILIAR_FAM
ORDER BY b.DOC_NU_CPF_PESSOA;
