/* ============================================================================
   OBJETIVO:
     Retornar DOC + PESSOA + FAMILIA + CONTATO_09
     filtrando por CODIBGE (UF2 + MUNIC5).

   COMO USAR:
     - Troque o schema mensal (P_CADASTRO_ODS_YYYYMM) nos FROM/JOIN.
     - Ajuste o CODIBGE_ALVO no CTE params (ex: '5300108').

   NOTA:
     - Retorna TODAS as ocorrências (histórico). Se quiser deduplicar, me diga
       qual regra (ex.: pegar só CO_EST_CADASTRAL_MEMB=3 e mais recente).
   ============================================================================ */

DATABASE P_CADASTRO_ODS_202601;

WITH params AS (
  SELECT
    '5200258' AS CODIBGE_ALVO   -- <<< INFORME AQUI O CODIBGE (7 dígitos)
)
SELECT
    /* ========== TB_DOCUMENTO_05 ========== */
    DOC.CO_FAMILIAR_FAM           AS DOC_CO_FAMILIAR_FAM,
    DOC.CO_CHV_NATURAL_PESSOA     AS DOC_CO_CHV_NATURAL_PESSOA,
    DOC.NU_CPF_PESSOA             AS DOC_NU_CPF_PESSOA,
    DOC.CO_CERTIDAO_CIVIL_PESSOA  AS DOC_CO_CERTIDAO_CIVIL_PESSOA,
    DOC.NO_CARTORIO_PESSOA        AS DOC_NO_CARTORIO_PESSOA,
    DOC.NU_IDENTIDADE_PESSOA      AS DOC_NU_IDENTIDADE_PESSOA,
    DOC.SG_UF_IDENT_PESSOA        AS DOC_SG_UF_IDENT_PESSOA,
    DOC.NU_TITULO_ELEITOR_PESSOA  AS DOC_NU_TITULO_ELEITOR_PESSOA,

    /* ========== TB_PESSOA_04 ========== */
    P.CO_FAMILIAR_FAM             AS PES_CO_FAMILIAR_FAM,
    P.CO_CHV_NATURAL_PESSOA       AS PES_CO_CHV_NATURAL_PESSOA,
    P.DT_CADASTRAMENTO_MEMB       AS PES_DT_CADASTRAMENTO_MEMB,
    P.DT_ATUAL_MEMB               AS PES_DT_ATUAL_MEMB,
    P.CO_EST_CADASTRAL_MEMB       AS PES_CO_EST_CADASTRAL_MEMB,
    P.NO_PESSOA                   AS PES_NO_PESSOA,
    P.NU_NIS_PESSOA               AS PES_NU_NIS_PESSOA,
    P.NO_APELIDO_PESSOA           AS PES_NO_APELIDO_PESSOA,
    P.DT_NASC_PESSOA              AS PES_DT_NASC_PESSOA,
    P.CO_ORIGEM_FAMILIA_PESSOA    AS PES_CO_ORIGEM_FAMILIA_PESSOA,
    P.IN_ORIGEM_ALTERACAO_PESSOA  AS PES_IN_ORIGEM_ALTERACAO_PESSOA,
    P.CO_CHV_NAT_PES_ATUAL        AS PES_CO_CHV_NAT_PES_ATUAL,
    P.CO_CHV_NAT_PES_ORIGINAL     AS PES_CO_CHV_NAT_PES_ORIGINAL,
    P.NU_NIS_ORIGINAL             AS PES_NU_NIS_ORIGINAL,
    P.IN_TRANSFERENCIA_PESSOA     AS PES_IN_TRANSFERENCIA_PESSOA,

    /* ========== TB_FAMILIA_01 ========== */
    F.CO_FAMILIAR_FAM             AS FAM_CO_FAMILIAR_FAM,
    F.DT_CADASTRO_FAM             AS FAM_DT_CADASTRO_FAM,
    F.DT_ULT_ATUAL_FAM            AS FAM_DT_ULT_ATUAL_FAM,
    F.CO_EST_CADASTRAL_FAM        AS FAM_CO_EST_CADASTRAL_FAM,
    F.IN_CADASTRO_VALIDO_FAM      AS FAM_IN_CADASTRO_VALIDO_FAM,
    F.CO_CONDICAO_CADASTRO_FAM    AS FAM_CO_CONDICAO_CADASTRO_FAM,
    F.CO_MODALIDADE_OPER_FAM      AS FAM_CO_MODALIDADE_OPER_FAM,
    F.CO_ORIGEM_FAMILIA_FAM       AS FAM_CO_ORIGEM_FAMILIA_FAM,
    F.DT_CDSTR_ATUAL_FMLA         AS FAM_DT_CDSTR_ATUAL_FMLA,
    F.IN_FAM_ALTERADA_V7          AS FAM_IN_FAM_ALTERADA_V7,
    F.DT_ATUALIZACAO_FAM          AS FAM_DT_ATUALIZACAO_FAM,

    /* ========== TB_CONTATO_09 ========== */
    CONT.NU_DDD_CONTATO_1_FAM      AS CONT_DDD_1,
    CONT.NU_TEL_CONTATO_1_FAM      AS CONT_TEL_1,
    CONT.NU_DDD_CONTATO_2_FAM      AS CONT_DDD_2,
    CONT.NU_TEL_CONTATO_2_FAM      AS CONT_TEL_2,
    CONT.IN_TIPO_EMAIL_FAM         AS CONT_TIPO_EMAIL,
    CONT.DS_EMAIL_FAM              AS CONT_EMAIL,

    /* (extra) CODIBGE calculado (para conferência) */
    LPAD(TRIM(CAST(F.CO_MUNIC_IBGE_2_FAM AS VARCHAR(2))), 2, '0')
    || LPAD(TRIM(CAST(F.CO_MUNIC_IBGE_5_FAM AS VARCHAR(5))), 5, '0') AS CODIBGE

FROM P_CADASTRO_ODS_202601.TB_DOCUMENTO_05 DOC
JOIN P_CADASTRO_ODS_202601.TB_PESSOA_04 P
  ON P.CO_CHV_NATURAL_PESSOA = DOC.CO_CHV_NATURAL_PESSOA
JOIN P_CADASTRO_ODS_202601.TB_FAMILIA_01 F
  ON F.CO_FAMILIAR_FAM = P.CO_FAMILIAR_FAM
LEFT JOIN P_CADASTRO_ODS_202601.TB_CONTATO_09 CONT
  ON CONT.CO_FAMILIAR_FAM = P.CO_FAMILIAR_FAM
CROSS JOIN params prm

WHERE
  /* filtro do município-alvo */
  ( LPAD(TRIM(CAST(F.CO_MUNIC_IBGE_2_FAM AS VARCHAR(2))), 2, '0')
    || LPAD(TRIM(CAST(F.CO_MUNIC_IBGE_5_FAM AS VARCHAR(5))), 5, '0')
  ) = prm.CODIBGE_ALVO

  /* opcional: se quiser ignorar linhas sem CPF */
  AND DOC.NU_CPF_PESSOA IS NOT NULL

-- Se você quiser restringir ao "universo ativo", descomente:
  AND F.CO_EST_CADASTRAL_FAM NOT IN (1,2,4)
  AND P.CO_EST_CADASTRAL_MEMB = 3


ORDER BY DOC.NU_CPF_PESSOA, P.CO_CHV_NATURAL_PESSOA, P.CO_FAMILIAR_FAM;
